# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under the MIT license

language: cpp
dist: trusty

addons:
  apt:
    sources:
    # Clang 7:
      - llvm-toolchain-trusty-7
      - ubuntu-toolchain-r-test
    packages:
      - clang-7
      - doxygen
      - graphviz
    # For building gtest:
      - cmake

script:
  - set -e
  - GTEST_VERSION=1.8.1
    ; GTEST_PREFIX=~/.local/
    ; wget https://github.com/google/googletest/archive/release-${GTEST_VERSION}.tar.gz
    && tar xf release-${GTEST_VERSION}.tar.gz
    && ( cd googletest-release-${GTEST_VERSION}/
      && cmake -DCVF_VERSION=${GTEST_VERSION} -DCMAKE_INSTALL_PREFIX:PATH=${GTEST_PREFIX} .
      && make
      && make install )
    && export PKG_CONFIG_PATH="$(find "${GTEST_PREFIX}" -type d -name pkgconfig)"
  - sed 's,-I,-isystem ,g' -i "${PKG_CONFIG_PATH}"/gtest.pc  # suppress compile warnings
  - ./autogen.sh
  - compile_flags=(
        -pipe

        -O1
        -g
        -fsanitize=address
        -fno-omit-frame-pointer

        -Wall
        -Wextra
        -pedantic
    )
    && CFLAGS="${compile_flags[*]} -std=c89"
    && CXXFLAGS="${compile_flags[*]} -std=c++98"
    && configure_args=(
        CC=clang-7
        CXX=clang++-7
        CFLAGS="${CFLAGS}"
        CXXFLAGS="${CXXFLAGS}"
        LDFLAGS='-g -fsanitize=address'
    )
    && ./configure "${configure_args[@]}"  # -Werror would fail configure checks!
  - make CFLAGS="${CFLAGS} -Werror" CXXFLAGS="${CXXFLAGS} -Werror" all
  - make CFLAGS="${CFLAGS} -Werror" CXXFLAGS="${CXXFLAGS} -Werror" check
  - cat test/uriparser_test.log
  - make distcheck  # without Address Sanitizer
